### ISSUE TITLE
contract link goes to wrong contract on quipuswap. 

### ISSUE THREAD

**Issue by sebuhbitcoin** [bender-labs/wrap-liquidity-mining#7]
![image](https://user-images.githubusercontent.com/5566620/118363367-e342a300-b548-11eb-8796-b36fa1d8372d.png)
After clicking this button it leads to the wrong page,

It links to https://quipuswap.com/invest/add-liquidity/KT1Lvtxpg4MiT2Bs38XGxwh3LGi5MkCENp4v

when it should link to https://quipuswap.com/invest/add-liquidity/KT18fp5rcTW7mbWDmzFwjLDUhs5MeJmagDSZ_0

![image](https://user-images.githubusercontent.com/5566620/118363522-a034ff80-b549-11eb-8481-7fd78c7c7893.png)

**Comment by sebuhbitcoin** [comment]
href={`https://quipuswap.com/invest/add-liquidity/${program.pool.contract}_${program.pool.base.id}`}

im not sure how to do a pull request just yet, im just starting out in development coding.

What i found is this seems to fix the issue, 
wrap-liquidity-mining/src/features/farming/components/FarmingContractInfo.tsx /
line 22

**Comment by BodySplash** [comment]
It seems quipuswap has changed its url scheme. We will look into it, thanks for the feedback.
